### PR TITLE
Support Scroll to Header In Editor Mode

### PR DESCRIPTION
**Pull request by jerrylususu**
Addressed #42 .

The scroll to header now works both in editor mode and preview mode. If both mode is visible (split mode), the editor is of higher priority than previewer.

How it works:
* First in `mdHeaders` method, saves not only hash but also line number.
* Then use CodeMirror's `charCoords` method with line number as parameter to get the target coordinate
* Finally use CodeMirror's `scrollTo` method to scroll to the target coordinate.
* Uses global setting `editor.codeView` to decide whether editor is visible.

Note:
* Sometimes the first `charCoords` call returns an incorrect coordinate with around 10px error. Perform twice `charCoords` and `scrollTo` fixes the problem.
image

Demo:
joplin_outline_new

### CODE REVIEW

**Comment by cqroot** [comment]
I will merge it after the test is complete.

**Comment by cqroot** [comment]
Under the editor layout, split layout, and WYSIWYG editor, it can work normally, except for viewer layout.

Scrolling in the viewer layout is not working.

In the viewer layout, the value of `editor.codeView` is true, and `scrollToLineTop` is executed, which is unreasonable. 

pr43

**Comment by jerrylususu** [comment]
Thanks for finding out this bug. It seems that in viewer mode `scrollToHash` is the correct method to use. I just checked all the `globalValues` and found that `noteVisiblePanes` seems to indicate the status of editor and viewer. It's an array, and in editor mode it only contains `editor`, in viewer mode it only contains `viewer` and in split mode it contains both. By adding an additional if check the issue is now fixed. 


joplin_outline_viewer

**Comment by cqroot** [comment]
@all-contributors please add @jerrylususu  for code.

**Pull request merged**
